#!/bin/bash
#
# Automatically set basic info: timezone, umask.
# Author: Guangyu Peng

echo "######################## Start basic set #########################"
set -xe

TIMEZONE_FILE="/usr/share/zoneinfo/Asia/Shanghai"

sudo ln -sf "${TIMEZONE_FILE}" /etc/localtime

echo "umask 0022" >> "${HOME}/.bashrc"

chmod 750 "${HOME}"

set +x
echo "######################## Basic set done ##########################"