#!/bin/bash
#
# Automatically add configuration files for common developmental tools.
# Author: Guangyu Peng

echo "######################## Configure tools #########################"
set -xeu

source "${SHELLREPOPATH}/lib/sh/utils.sh"
os_name="$(get_os_name)"
ETC_DIR="${SHELLREPOPATH}/init/etc"

cp "${ETC_DIR}/dir_colors" ~/.dir_colors
cp "${ETC_DIR}/my_env" ~/.my_env
cp "${ETC_DIR}/p10k.zsh" ~/.p10k.zsh
cp "${ETC_DIR}/tmux.conf" ~/.tmux.conf
cp "${ETC_DIR}/zshrc" ~/.zshrc

echo "export SHELLREPOPATH=\"${SHELLREPOPATH}\"" >> ~/.my_env
echo "[[ ! -f ~/.my_env ]] || source ~/.my_env" >> ~/.bashrc

# git
git config --global user.name "GuangyuPeng"
git config --global user.email "gypeng2021@163.com"
git config --global core.editor vim
git config --global init.defaultBranch main

# ssh
mkdir -p ~/.ssh
chmod 700 ~/.ssh
cp -rf "${ETC_DIR}"/ssh/* ~/.ssh/

# config
mkdir -p ~/.config
cp -rf "${ETC_DIR}"/config/* ~/.config/

# vim
mkdir -p ~/.vim
chmod 750 ~/.vim
cp -rf "${ETC_DIR}"/vim/* ~/.vim/

if ! echo "${os_name}" | grep -q 'macos'; then
  fc-cache -f -v
fi

set +x
echo "######################## Configure done ##########################"
