#!/bin/bash
#
# Back up all users' files in /home/<user_name>.
# To ignore some users, edit variable 'EXCLUDE_USERS'.
# Author: Guangyu Peng

set -eu

EXCLUDE_USERS=()

checkroot() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "You need to run this script as root." >&2
    exit 1
  fi
}

main() {
  local usage="Usage: $0 backup_file_path"
  checkroot
  if (($# < 1)); then
    echo "${usage}" >&2
    exit 1
  fi
  tar_file_path="$1"
  
  user_names=$(awk -F ':' '$3>=1000 && $1!="nobody" {print $1}' /etc/passwd)
  user_names=(${user_names})
  
  for exclude_user in "${EXCLUDE_USERS[@]}"; do
    user_names=(${user_names[@]/${exclude_user}})
  done
  
  user_homes_str=""
  for user_name in "${user_names[@]}"; do
    user_homes_str="${user_homes_str} /home/${user_name}"
  done

  echo "These directories will be backed up:"
  echo "${user_homes_str}"
  while true; do
    read -p "Will we go on (Yes/No)? " yn
    case "${yn}" in
      [Yy]es)
        echo "Back up to ${tar_file_path}"
        tar -zcvf "${tar_file_path}" ${user_homes_str}
        break
        ;;
      [Nn]o)
        echo "Stop script."
        break
        ;;
      *)
        echo "Please answer yes or no."
        ;;
    esac
  done
}

main "$@"