#!/bin/bash
#
# Create a user with username and identity file.
# Author: Guangyu Peng

set -eu

checkroot() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "You need to run this script as root." >&2
    exit 1
  fi
}

main() {
  local usage="Usage: $0 username identity_file"
  checkroot
  if (($# < 2)); then
    echo "${usage}"
    exit 1
  fi
  username="$1"
  identity_file="$2"
  useradd -m -s /bin/bash "${username}"
  homedir=$(getent passwd "${username}" | cut -d: -f6)
  chmod 750 "${homedir}"
  mkdir -p "${homedir}/.ssh"
  cat "${identity_file}" >> "${homedir}/.ssh/authorized_keys"
  chmod 700 "${homedir}/.ssh"
  chmod 600 "${homedir}/.ssh/authorized_keys"
  chown -R "${username}:${username}" "${homedir}/.ssh"
  # set password
  echo "${username}:${username}" | chpasswd
  # require to change password on first login
  chage -d 0 "${username}"

  while true; do
    read -p "Grant sudo privileges to user ${username} (Yes/No)? " yn
    case "${yn}" in
      [Yy]*)
        echo "Grant sudo privileges"
        usermod -aG sudo "${username}"
        break
        ;;
      [Nn]*)
        echo "Not grant sudo privileges"
        break
        ;;
      *)
        echo "Please answer yes or no."
        ;;
    esac
  done
}

main "$@"