#!/bin/bash
#
# Automatically install kubernetes tools.
# Author: Guangyu Peng
set -eu
source "${SHELLREPOPATH}/lib/sh/utils.sh"

apt_install_kubectl() {
  apt -y update
  apt install -y ca-certificates curl
  # Download the Google Cloud public signing key
  curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg \
    https://packages.cloud.google.com/apt/doc/apt-key.gpg
  # Add the Kubernetes apt repository
  echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] \
    https://apt.kubernetes.io/ kubernetes-xenial main" | \
    tee /etc/apt/sources.list.d/kubernetes.list
  # Install kubectl
  apt -y update
  apt install -y kubectl
  # Check version
  kubectl version --client
}

dpkg_install_minikube() {
  cd /tmp
  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
  dpkg -i minikube_latest_amd64.deb
}

main() {
  checkroot
  os_name="$(get_os_name)"
  if echo "${os_name}" | grep -q 'centos'; then
    # TODO: install developmental tools on centos
    :
  elif echo "${os_name}" | grep -q 'ubuntu'; then
    apt_install_kubectl
    dpkg_install_minikube
  fi
}

main "$@"